
app:
  name: migrate-bundles
  dir: ${user.home}/.${app.name}
  csv-dir: ${user.home}/tmp/bundles-csv
  basenames-filename: bundles_public_basenames.csv
  db-host: localhost
  db-name: bundles
  db-username: postgres
  db-password: postgres
  db-port: 5432
  db-url-prefix: jdbc:postgresql://

spring:
  main:
    web-application-type: none
  batch:
    initialize-schema: always
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: ${app.db-url-prefix}${app.db-host}:${app.db-port}/${app.db-name}
    jdbcUrl: ${spring.datasource.url}
    username: ${app.db-username}
    password: ${app.db-password}
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      generate_statistics: false
      jdbc:
        batch_size: 5
        batch_versioned_data: true
      show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
